//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ozzFIT_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Comments
    {
        public int CommentId { get; set; }
        [AllowHtml]
        public string CDescription { get; set; }
        public string CDateTime { get; set; }
        public Nullable<int> EventEventId { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
