//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ozzFIT_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int ConsultationId { get; set; }
        public System.DateTime StartDT { get; set; }
        public System.DateTime EndDT { get; set; }
        public string RDescription { get; set; }
        public string Status { get; set; }
        public int UserUserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
