//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ozzFIT_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int EmailId { get; set; }
        public string ToEmail { get; set; }
        public string Subject { get; set; }
        public string Contents { get; set; }
        public int EventEventId { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
