//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ozzFIT_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventReport
    {
        public int EventReportId { get; set; }
        public string EventName { get; set; }
        public string ReportDescription { get; set; }
        public Nullable<bool> ReportMedia { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
