//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ozzFIT_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSVP
    {
        public int RSVPId { get; set; }
        public string RSVPStatus { get; set; }
        public long NumOfGuests { get; set; }
        public int EventMemberEventEventId { get; set; }
        public int EventMemberUserUserId { get; set; }
    
        public virtual EventMember EventMember { get; set; }
    }
}
