//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_ozzFIT_V2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDatabaseModel1Container : DbContext
    {
        public UserDatabaseModel1Container()
            : base("name=UserDatabaseModel1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventMember> EventMembers { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Consultation> Consultations { get; set; }
    }
}
